name: Endor Labs - SCA Scan on PR
on:
  workflow_dispatch:
  pull_request: # <-- uncomment/comment out to enable/disable pr scans 
    
jobs:
  scan-repo:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      issues: write
      pull-requests: write
      contents: read
    steps:

        - name: Checkout Repository
          uses: actions/checkout@v3
          
        - name: Setup Java
          uses: actions/setup-java@v4
          with:
            distribution: microsoft
            java-version: "17"
            cache: maven
            cache-dependency-path: pom.xml

        - name: Compile Package
          run: mvn clean install
            
        - name: Endor Labs Workflow Dispatch
          uses: endorlabs/github-action@main
          with:
            namespace: "matt-demo"
            api: "https://api.endorlabs.com"
            scan_summary_output_type: "table"
            enable_pr_comments: true
            enable_github_action_token: true
            github_token: ${{ secrets.GH_TOKEN }}
