name: Endor Labs - Container Scan and Release

on:
  workflow_dispatch
  
jobs:
  release:
    name: Build and Sign
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Build JAR
        run: mvn clean install -Dskiptests=true

      - name: Create container
        run: docker build -t endormatt/app-java-demo:latest .
          
      - name: Get Image Digest to Sign
        run: |
         IMAGE_SHA=$(docker inspect endormatt/app-java-demo:latest | jq -r '.[].Id')
         IMAGE_NAME=endormatt/app-java-demo
         SIGNING_TARGET="$IMAGE_NAME"@"$IMAGE_SHA"
         echo ARTIFACT="$SIGNING_TARGET" >> $GITHUB_ENV

      - name: Container Sign
        uses: endorlabs/github-action/sign@main
        with:
          namespace: "matt-demo-2"
          artifact_name: ${{ env.ARTIFACT }}

      - name: Run Tests
        run: |
          mvn test
          
      - name: Endor Labs Scan
        uses: endorlabs/github-action@main
        with:
          namespace: "matt-demo-2"
          scan_summary_output_type: "table"
          pr: "false"
          enable_github_action_token: "true"
          scan_dependencies: "true"
          scan_secrets: "true"
          scan_git_logs: "true"
          scan_tools: "true"

      - name: Run SAST
        run: python3 -m pip install semgrep && semgrep scan
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get Image Digest to Verify
        run: |
         VERIFY_SHA=$(docker inspect endormatt/app-java-demo:latest | jq -r '.[].Id')
         VERIFY_IMAGE_NAME=endormatt/app-java-demo
         VERIFY_TARGET="$VERIFY_IMAGE_NAME"@"$VERIFY_SHA"
         echo VERIFY_ARTIFACT="$VERIFY_TARGET" >> $GITHUB_ENV
         
      - name: Container verify
        uses: endorlabs/github-action/verify@main
        with:
          namespace: "matt-demo-2"
          artifact_name: ${{ env.VERIFY_ARTIFACT }}
          certificate_oidc_issuer: "https://token.actions.githubusercontent.com"
      
      - name: Capture Container verify log
        run: |
          endorlabs/github-action/verify@main | tee $OUTPUT_LOG
  
      - name: Extract and set ARTIFACT_SIGNATURE
        id: extract_signature
        run: |
          signature=$(grep 'Signature:' $OUTPUT_LOG | awk '{print $2}')
          echo "ARTIFACT_SIGNATURE=$signature" >> $GITHUB_ENV

      - name: Push to Docker Hub
        run: docker push endormatt/app-java-demo:latest

      - name: Endor Labs Container Scan
        uses: endorlabs/github-action@containers
        with:
          namespace: "matt-demo"
          scan_summary_output_type: "table"
          pr: true
          enable_github_action_token: true
          scan_container: true
          scan_dependencies: false
          github_token: ${{ secrets.GH_TOKEN }} 
          enable_pr_comments: true
          image: endormatt/app-java-demo:latest
          project_name: container-matt-app-java-demo
          tags: "Artifact Signature = ${{ env.ARTIFACT_SIGNATURE }}"
          
